name: resinstaller-premake5-ubuntu

on:
  workflow_dispatch:
  push:
    paths:
      - 'resinstaller/src/**'
      - '.github/workflows/resinstaller-premake5-ubuntu.yml'
      - 'resinstaller/premake5.lua'

  pull_request:
    paths:
      - 'resinstaller/src/**'
      - '.github/workflows/resinstaller-premake5-ubuntu.yml'
      - 'resinstaller/premake5.lua'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: apt-get update
      run: sudo apt-get update

    - name: install dependencies SDL2 ogg vorbis
      run: |
        sudo apt-get install libsdl2-dev libogg-dev libvorbis-dev libvorbisenc2 libvorbisidec-dev

    - name: checkout premake5
      uses: actions/checkout@v3
      with:
          repository: premake/premake-core
          path: premake-build

    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak linux CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build

    - name: run premake5
      run: ./premake5 --file=resinstaller/premake5.lua gmake2 --to=../solution/gmake2/resinstaller

    - name: build
      run: |
        cd solution/gmake2/resinstaller/
        make config=release resinstaller
