name: resinstaller-premake5-macos

on:
  workflow_dispatch:
  push:
    paths:
      - 'resinstaller/src/**'
      - '.github/workflows/resinstaller-premake5-macos.yml'
      - 'resinstaller/premake5.lua'

  pull_request:
    paths:
      - 'resinstaller/src/**'
      - '.github/workflows/resinstaller-premake5-macos.yml'
      - 'resinstaller/premake5.lua'

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: install dependencies SDL2 ogg vorbis
      run: brew install sdl2 libogg libvorbis

    - name: checkout premake5
      uses: actions/checkout@v3
      with:
          repository: premake/premake-core
          path: premake-build

    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak osx CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build

    - name: run premake5
      run: ./premake5 --file=resinstaller/premake5.lua xcode4 --to=../solution/xcode4/resinstaller

    - name: build
      run: |
        cd solution/xcode4/resinstaller/
        xcodebuild -project resinstaller.xcodeproj -configuration Release -scheme resinstaller build
